### ISSUE TITLE
permission denied when creating folders

### ISSUE THREAD

**Issue by sueyhan** [caffe2/models#16]
I tried to follow the instruction of downloading models and installing them locally by
`python -m caffe2.python.models.download -i squeezenet`
But I got permission denied and error like this:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/caffe2/python/models/download.py", line 174, in <module>
    downloadModel(model, args)
  File "/usr/local/caffe2/python/models/download.py", line 136, in downloadModel
    os.makedirs(model_folder)
  File "/home/ubuntu/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/caffe2/python/models/squeezenet'

It might be python is not authorized to create directory

**Comment by Maratyszcza** [comment]
You do not have write access to directory `/usr/local/caffe2/python/models/`. If you are on Linux, this is kind of expected; if you are on Mac, you probably did `sudo make install` for Caffe2, and as a result `/usr/local/caffe2` does not belong to your user account.

Either way, the following commands should help:
```
sudo mkdir -p /usr/local/caffe2/python/models
sudo chown -R $USER /usr/local/caffe2/python/models
```

**Comment by sueyhan** [comment]
Thanks! It works
