### ISSUE TITLE
Detectron e2e_faster_rcnn_R-50-C4_1x enforce fail at generate_proposals_op.cc:205

### ISSUE THREAD

**Issue by dcompgriff** [caffe2/models#34]
results = p.run([img])
Hello. I am trying to run the facebook detectron network following the basic tutorial for loading and using a pre-trained network (swapping out the information for detectron rather than squeezenet) and am running into the following error:

Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-f0974de83af0>", line 1, in <module>
    results = p.run([img])

RuntimeError: [enforce fail at generate_proposals_op.cc:205] im_info_tensor.dims() == (vector<TIndex>{num_images, 3}). 0 vs 1 3 Error from operator: 
input: "rpn_cls_probs" input: "rpn_bbox_pred" input: "im_info" input: "anchor" output: "rpn_rois" output: "rpn_roi_probs" name: "" type: "GenerateProposals" arg { name: "nms_thres" f: 0.7 } arg { name: "min_size" f: 0 } arg { name: "spatial_scale" f: 0.0625 } arg { name: "correct_transform_coords" i: 1 } arg { name: "post_nms_topN" i: 1000 } arg { name: "pre_nms_topN" i: 6000 }

Looking at the network definition, there seems to be an object called "im_info" that is supposedly externally generated. I however cannot figure out where or how this object should be initialized, or if it is actually being initialized. Either way, there seems to be an issue with verifying the size of the im_info_tensor blob when the data reaches the region proposal portion of the network.

**Comment by dcompgriff** [comment]
Ok. So, after playing around with the network and looking back at the original facebook detectron code, I found this line in the detectron to .pb conversion code:
```
    blobs['data'] = blob
    blobs['im_info'] = np.array(
        [[blob.shape[2], blob.shape[3], im_scale]],
        dtype=np.float32
        )
```
I translated this to the equivalent in caffe2, where my image size is 800x800, and 
I set the image scale arbitrarily to 1:
```
results = p.run({'data': img, 'im_info': np.array(
        [[800, 800, 1]],
        dtype=np.float32
)})
```
I'm new to caffe2, and wanted to run the facebook detectron code without needing a gpu. I think that a bit more guidance should be added to the README for the detectron models that specifies that an "im_info" object will also need to be passed to be able to perform object detection with the network.
