### ISSUE TITLE
Error installing model

### ISSUE THREAD

**Issue by m00nkeh** [caffe2/models#8]
On Windows, the command 'python -m caffe2.python.models.download -i squeezenet' fails with the error "'module' object has no attribute 'symlink'. It is my understanding that symlink is not available on non-Unix OSes.

**Comment by m00nkeh** [comment]
I've got the script to run by replacing the line `os.symlink("{folder}/__sym_init__.py".format(folder=dir_path),"{folder}/__init__.py".format(folder=model_folder))` with `win32file.CreateSymbolicLink("{folder}/__init__.py".format(folder=model_folder), "{folder}/__sym_init__.py".format(folder=dir_path), 1)` in download.py (and adding 'import win32file'), but when I try to import squeezenet from caffe2.python.models it fails.

I think my source and target may be the wrong way round, but if I swap them I get an error about creating a file that already exists.

**Comment by m00nkeh** [comment]
I replaced the 1 flag passed to CreateSymbolicLink with a 0 and that seems to have fixed it.

**Comment by blateyang** [comment]
@orionr When I use "python -m caffe2.python.models.download -i resnet50" to install resnet50 model, I ran into following problem:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ygj/caffe2/build/caffe2/python/models/download.py", line 176, in <module>
    print("'{model}' is not a valid model name.".format(model))
KeyError: u'model'`
I find it is because there is a small bug in line 157 of  download.py,i.e `if not re.match("^[a-zA-Z_]+$", name):`. '$' should be remove, otherwise the model name with num ending can't be correctly install.
